export default {
    '上胶': {
        columnRecords: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '涂覆次数',
            prop: 'coatingCount',
        }, {
            label: '胶水',
            align: 'center',
            children: [{
                label: '比重',
                prop: 'glueProportion',
            }, {
                label: '粘度',
                prop: 'glueViscosity',
            }, {
                label: 'PH/温度',
                prop: 'gluePhTemperature',
            }]
        }, {
            label: '胶片重量g/cm²',
            align: 'center',
            children: [{
                label: '左',
                prop: 'glueWeightLeft',
            }, {
                label: '中',
                prop: 'glueWeightMiddle',
            }, {
                label: '右',
                prop: 'glueWeightRight',
            }]
        }, {
            label: '烘箱温度℃',
            align: 'center',
            children: [{
                label: '1区/2区',
                prop: 'ovenTemperatureFirst',
            }, {
                label: '3区/4区',
                prop: 'ovenTemperatureThird',
            }, {
                label: '5区/6区',
                prop: 'ovenTemperatureFifth',
            }, {
                label: '记录时间',
                prop: 'ovenWorkDate',
            }]
        }, {
            label: '顶轮温度℃',
            prop: 'wheelTemperature',
        }, {
            label: '胶片外观',
            prop: 'appearance',
        }, {
            label: '布/半制品基重g/㎡/RC',
            prop: 'halfBlankWeight'
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiRecords: '/productionexe/putglueprodrecord/page',
        addRecords: '/productionexe/putglueprodrecord/save',
        updateRecords: '/productionexe/putglueprodrecord/updateById',
        columnParams: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '机速M/min',
            prop: 'machineSpeed',
        }, {
            label: '张力设定',
            align: 'center',
            children: [{
                label: '放卷',
                prop: 'unwindingEffort',
            }, {
                label: '含浸',
                prop: 'immersionEffort',
            }, {
                label: '烘箱',
                prop: 'ovenEffort',
            }, {
                label: '收卷',
                prop: 'windingEffort',
            }]
        }, {
            label: '计量杆',
            align: 'center',
            children: [{
                label: '上1位置/φ',
                prop: 'positionFirst',
            }, {
                label: '2位置/φ',
                prop: 'positionSecond',
            }, {
                label: '3位置/φ',
                prop: 'positionThird',
            }, {
                label: '下4位置/φ',
                prop: 'positionFourth',
            }]
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiParams: '/productionexe/putglueprodparams/page',
        addParams: '/productionexe/putglueprodparams/save',
        updateParams: '/productionexe/putglueprodparams/updateById',
    },
    '混胶': {
        columnRecords: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '胶水型号',
            prop: 'glueModel',
        }, {
            label: '原液比重',
            prop: 'stosteProportion',
        }, {
            label: '固含量',
            prop: 'solidsContent',
        }, {
            label: '原液PH值',
            prop: 'stostePh',
        }, {
            label: '胶水PH值',
            prop: 'gluePh',
        }, {
            label: '胶水温度',
            prop: 'glueTemperature',
        }, {
            label: '胶水比重',
            prop: 'glueProportion'
        }, {
            label: '胶水粘度',
            prop: 'glueViscosity',
        }, {
            label: 'DI水电导率',
            prop: 'diConductivity'
        }, {
            label: '操作员',
            prop: 'operator'
        }],
        apiRecords: '/productionexe/mixglueprodrecord/page',
        addRecords: '/productionexe/mixglueprodrecord/save',
        updateRecords: '/productionexe/mixglueprodrecord/updateById',
        columnParams: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '搅拌速度',
            prop: 'agitationSpeed',
        }, {
            label: '搅拌开始时间',
            prop: 'agitateStartTime',
        }, {
            label: '搅拌结束时间',
            prop: 'agitateEndTime',
        }, {
            label: '低速搅拌转速',
            prop: 'lowSpeedAgitationSpeed',
        }, {
            label: '低速搅拌开始时间',
            prop: 'lowSpeedAgitationStartTime',
        }, {
            label: '低速搅拌结束时间',
            prop: 'lowSpeedAgitationEndTime',
        }, {
            label: '操作员',
            prop: 'operator'
        }],
        apiParams: '/productionexe/mixglueprodparams/page',
        addParams: '/productionexe/mixglueprodparams/save',
        updateParams: '/productionexe/mixglueprodparams/updateById',
    },
    '层压': {
        columnRecords: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '实际温度',
            prop: 'ambientTemperature',
        }, {
            label: '实际真空',
            prop: 'vacuum',
        }, {
            label: '实际压力',
            prop: 'pressure',
        }, {
            label: '机械表压力',
            prop: 'mechanicalPressure',
        }, {
            label: '料温',
            prop: 'materialTemperature'
        }, {
            label: '氮气压力值',
            prop: 'nitrogenPressure'
        }, {
            label: '班组',
            prop: 'classGroup'
        }, {
            label: '压合程式代码',
            prop: 'compressionCode'
        }, {
            label: '产品模号',
            prop: 'prodModelNo'
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiRecords: '/productionexe/laminationprodrecord/page',
        addRecords: '/productionexe/laminationprodrecord/save',
        updateRecords: '/productionexe/laminationprodrecord/updateById',
        columnParams: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '配方程式',
            prop: 'formulaProgram',
        }, {
            label: '压合程式',
            prop: 'tableProgram',
        }, {
            label: '压合开始时间',
            prop: 'workStartTime',
        }, {
            label: '压合结束时间',
            prop: 'workEndTime',
        }, {
            label: '温度设定',
            prop: 'setTemperature',
        }, {
            label: '压强设定',
            prop: 'setPressure',
        }, {
            label: '真空值设定',
            prop: 'setVacuuma',
        }, {
            label: '料温控制时的条件设定值',
            prop: 'materialTempController',
        }, {
            label: '产品模号',
            prop: 'prodModelNo',
        }, {
            label: '操作员',
            prop: 'setPressure',
        }],
        apiParams: '/productionexe/laminationprodparams/page',
        addParams: '/productionexe/laminationprodparams/save',
        updateParams: '/productionexe/laminationprodparams/updateById',
    },
    '铜箔裁切': {
        columnRecords: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '首件尺寸',
            prop: 'firstPieceSize',
        }, {
            label: '裁切速度',
            prop: 'cuttingSpeed',
        }, {
            label: '裁切距离',
            prop: 'cuttingDistance',
        }, {
            label: '输送带速度',
            prop: 'deliverySpeed',
        }, {
            label: '气涨轴A张力显示',
            prop: 'airAShow',
        }, {
            label: '气涨轴B张力显示',
            prop: 'airBShow',
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiRecords: '/productionexe/cuttingprodrecord/page',
        addRecords: '/productionexe/cuttingprodrecord/save',
        updateRecords: '/productionexe/cuttingprodrecord/updateById',
        columnParams: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '气涨轴A张力设定',
            prop: 'airASetting',
        }, {
            label: '气涨轴B张力设定',
            prop: 'airBSetting',
        }, {
            label: '输送带速度设定',
            prop: 'deliverySpeed',
        }, {
            label: '裁切规格',
            prop: 'cuttingSpecification',
        }, {
            label: '裁切速度设定',
            prop: 'cuttingSpeed',
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiParams: '/productionexe/cuttingprodparams/page',
        addParams: '/productionexe/cuttingprodparams/save',
        updateParams: '/productionexe/cuttingprodparams/updateById',
    },
    '离线PTFE裁切': {
        columnRecords: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '首件尺寸',
            prop: 'firstPieceSize',
        }, {
            label: '裁切速度',
            prop: 'cuttingSpeed',
        }, {
            label: '裁切距离',
            prop: 'cuttingDistance',
        }, {
            label: '输送带速度',
            prop: 'deliverySpeed',
        }, {
            label: '气涨轴A张力显示',
            prop: 'airAShow',
        }, {
            label: '气涨轴B张力显示',
            prop: 'airBShow',
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiRecords: '/productionexe/cuttingprodrecord/page',
        addRecords: '/productionexe/cuttingprodrecord/save',
        updateRecords: '/productionexe/cuttingprodrecord/updateById',
        columnParams: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '气涨轴A张力设定',
            prop: 'airASetting',
        }, {
            label: '气涨轴B张力设定',
            prop: 'airBSetting',
        }, {
            label: '输送带速度设定',
            prop: 'deliverySpeed',
        }, {
            label: '裁切规格',
            prop: 'cuttingSpecification',
        }, {
            label: '裁切速度设定',
            prop: 'cuttingSpeed',
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiParams: '/productionexe/cuttingprodparams/page',
        addParams: '/productionexe/cuttingprodparams/save',
        updateParams: '/productionexe/cuttingprodparams/updateById',
    },
    '离线PP裁切': {
        columnRecords: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '首件尺寸',
            prop: 'firstPieceSize',
        }, {
            label: '裁切速度',
            prop: 'cuttingSpeed',
        }, {
            label: '裁切距离',
            prop: 'cuttingDistance',
        }, {
            label: '输送带速度',
            prop: 'deliverySpeed',
        }, {
            label: '气涨轴A张力显示',
            prop: 'airAShow',
        }, {
            label: '气涨轴B张力显示',
            prop: 'airBShow',
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiRecords: '/productionexe/cuttingprodrecord/page',
        addRecords: '/productionexe/cuttingprodrecord/save',
        updateRecords: '/productionexe/cuttingprodrecord/updateById',
        columnParams: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '气涨轴A张力设定',
            prop: 'airASetting',
        }, {
            label: '气涨轴B张力设定',
            prop: 'airBSetting',
        }, {
            label: '输送带速度设定',
            prop: 'deliverySpeed',
        }, {
            label: '裁切规格',
            prop: 'cuttingSpecification',
        }, {
            label: '裁切速度设定',
            prop: 'cuttingSpeed',
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiParams: '/productionexe/cuttingprodparams/page',
        addParams: '/productionexe/cuttingprodparams/save',
        updateParams: '/productionexe/cuttingprodparams/updateById',
    },
    '手动组合': {
        columnRecords: [],
        apiRecords: '',
        addRecords: '',
        updateRecords: '',
        columnParams: [],
        apiParams: '',
        addParams: '',
        updateParams: '',
    },
    '手动分发': {
        columnRecords: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '班别',
            prop: 'className',
        }, {
            label: '底板编号',
            prop: 'baseboardNumber',
        }, {
            label: '钢板编号',
            prop: 'steelPlateNumber',
        }, {
            label: '钢板缺陷',
            align: 'center',
            children: [{
                label: '油污',
                prop: 'oilPollution',
            }, {
                label: '氧化',
                prop: 'oxidation',
            }, {
                label: '划痕',
                prop: 'scratch',
            }, {
                label: '杂质',
                prop: 'impurity',
            }, {
                label: '水印',
                prop: 'watermark',
            }]
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiRecords: '/productionexe/distributeprodrecord/page',
        addRecords: '/productionexe/distributeprodrecord/save',
        updateRecords: '/productionexe/distributeprodrecord/updateById',
        columnParams: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '班别',
            prop: 'className',
        }, {
            label: '线速',
            prop: 'lineSpeed',
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiParams: '/productionexe/distributeprodparams/page',
        addParams: '/productionexe/distributeprodparams/save',
        updateParams: '/productionexe/distributeprodparams/updateById',
    },
    '手动叠制': {
        columnRecords: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '生产批次号',
            disabled: true,
            prop: 'prodBatchNo',
        }, {
            label: 'book序号',
            prop: 'bookSn',
        }, {
            label: '重量（kg)',
            prop: 'weight',
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiRecords: '/productionexe/overlayprodrecord/page',
        addRecords: '/productionexe/overlayprodrecord/save',
        updateRecords: '/productionexe/overlayprodrecord/updateById',
        columnParams: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '叠制结构',
            prop: 'structure',
        }, {
            label: '叠制数量',
            prop: 'overlayCount',
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiParams: '/productionexe/overlayprodparams/page',
        addParams: '/productionexe/overlayprodparams/save',
        updateParams: '/productionexe/overlayprodparams/updateById',
    },
    '外观修边': {
        columnRecords: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '缺陷代码',
            prop: 'defectNo',
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiRecords: '/productionexe/deburringprodrecord/page',
        addRecords: '/productionexe/deburringprodrecord/save',
        updateRecords: '/productionexe/deburringprodrecord/updateById',
        columnParams: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '测厚仪设定值',
            prop: 'gaugeValue',
        }, {
            label: '测厚仪允差',
            prop: 'gaugeOffset',
        }, {
            label: '基板长度设定',
            prop: 'lengthSetting',
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiParams: '/productionexe/deburringprodparams/page',
        addParams: '/productionexe/deburringprodparams/save',
        updateParams: '/productionexe/deburringprodparams/updateById',
    },
    '包装': {
        columnRecords: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '包装纸长度显示',
            prop: 'packingPaperLength',
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiRecords: '/productionexe/packprodrecord/page',
        addRecords: '/productionexe/packprodrecord/save',
        updateRecords: '/productionexe/packprodrecord/updateById',
        columnParams: [{
            label: '序号',
            type: 'index',
            width: 50
        }, {
            label: '横向压合时间设定',
            prop: 'transverseCompressionTime',
        }, {
            label: '纵向压合时间设定',
            prop: 'portraitCompressionTime',
        }, {
            label: '自动速度设定',
            prop: 'autoSpeedSetting',
        }, {
            label: '手动速度设定',
            prop: 'manualSpeedSetting',
        }, {
            label: '托盘自动下降距离',
            prop: 'palletDescentDistance',
        }, {
            label: '边料卷曲时间',
            prop: 'sideCrimpingTime',
        }, {
            label: '吹气时间设定',
            prop: 'blowingTimeSetting',
        }, {
            label: '修正长度设定',
            prop: 'fixedLengthSetting',
        }, {
            label: '操作员',
            prop: 'operator',
        }],
        apiParams: '/productionexe/packprodparams/page',
        addParams: '/productionexe/packprodparams/save',
        updateParams: '/productionexe/packprodparams/updateById',
    },
};
